### ISSUE TITLE
Gemfile.lock of v7.5.1 was NOT update

### ISSUE THREAD

**Issue by lvii** [qwtel/hydejack-starter-kit#2]
Hi,

It seemed that `Gemfile.lock` was NOT updated from hydejack, it still used `jekyll (3.6.2)`:

https://github.com/qwtel/hydejack-starter-kit/blob/master/Gemfile.lock

https://github.com/qwtel/hydejack/blob/master/Gemfile.lock

**Comment by qwtel** [comment]
True. Thanks for reporting.
